src/ManageClient.php
src/Sandbox.php
tests/ClientTest.php

I also removed the deprecated port and added missing setSize

Add get manage call + had to change other manage calls (PS-332)

---

src/Sandbox.php

- added setting of expirationAfterHours, lastAutosaveTimestamp, mlflow in constructor
- added setters and getters of lastAutosaveTimestamp, mlflow
- added mlflow to toArray()
I rather reordered properties and their setting (according to the order in apidocs) to check that there is nothing forgotten.

Fix missing setters

---

src/Client.php
src/Sandbox.php
tests/ClientTest.php

And adapt to the generation of sandbox id in the api (https://github.com/keboola/sandboxes-api/pull/30)

feat: add update sandbox method (PS-574)

---

src/Sandbox.php

fix update sandbox

---

src/Sandbox.php

fix setting size

---

.github/workflows/build.yml

This will be the source of that failing GC in AZ testing 😄

Fix Cosmos endpoint in tests

---

src/Sandbox.php

Fix setting shared flag

---

src/Client.php
src/MLDeployment.php
src/ManageClient.php
tests/ClientTest.php

It will be released as a major version because I changed also the name of the MLDeployment class

Use /ml endpoints and update using PATCH

---

src/Sandbox.php
tests/ClientTest.php

I'm not sure, is it fine? I have a suspicion that from the purely OOP standpoint it maybe should have its own object. 😬

Allow saving databricks configuration in sandbox (PS-2338)

---

src/Sandbox.php

Fix save and get databricks configuration to api (PS-2338)

---

Dockerfile
composer.json
src/Sandbox.php
tests/ClientTest.php

https://keboola.atlassian.net/browse/PS-2840
Followup to https://github.com/keboola/sandboxes-api/pull/150

PS-2840 Store sandbox persistent storage configuration

---

.github/workflows/build.yml
docker-compose.yml
src/Project.php
tests/ClientTest.php

https://keboola.atlassian.net/browse/PS-2866
Depends on https://github.com/keboola/sandboxes-api/pull/151

PS-2866 Add project.mlflowAbsConnectionString

---

src/Sandbox.php
tests/ClientTest.php

https://keboola.atlassian.net/browse/PS-2836
Depends on: https://github.com/keboola/sandboxes-api/pull/155
Add sandbox.persistentStorage.k8sManifest to store a full PVC manifest Moments ago

PS-2917 sandbox.persistentStorage.k8sManifest

---

src/Sandbox.php
tests/ClientTest.php

https://keboola.atlassian.net/browse/PS-2990

PS-2990 add dbx clusterId

---

src/Client.php
src/ListOptions.php
src/Sandbox.php
tests/ClientFunctionalTest.php
tests/ClientTest.php
tests/ClientUnitTest.php
tests/ListOptionsTest.php

https://keboola.atlassian.net/browse/PS-1705

PS-1705 Sandboxes branchId

---

src/Sandbox.php

https://keboola.atlassian.net/browse/PS-3126
Needed for: https://github.com/keboola/sandboxes/pull/294

PS-3126 Identify sandbox types which uses Python

---

.github/workflows/build.yml
src/ManageClient.php
tests/ClientFunctionalTest.php

https://keboola.atlassian.net/browse/PS-3207

PS-3207 Notify branch deleted

---

src/Client.php
src/Project.php
tests/ClientFunctionalTest.php

Just fixes `updateProjectServerVersion()` to accept null

tests: serverVersion can be set to null

---

src/PersistentStorage.php
tests/ClientFunctionalTest.php
tests/PersistentStorageTest.php

https://keboola.atlassian.net/browse/PS-3373
Depends on: https://github.com/keboola/sandboxes-api/pull/176

PS-3373 Store project.persistentStorage.k8sStorageClassName

---

src/Project.php
tests/ClientFunctionalTest.php

https://keboola.atlassian.net/browse/PS-3371
Depnds on: https://github.com/keboola/sandboxes-api/pull/178

PS-3371 Add project.mlflowRequiresAuth flag

---

src/ListProjectsOptions.php
src/ManageClient.php
tests/ListProjectsOptionsTest.php
tests/ManageClientTest.php

https://keboola.atlassian.net/browse/PS-3375
Sandboxes API PR: https://github.com/keboola/sandboxes-api/pull/179

PS-3375 Add `ManageClient::listProjects`

---

.github/workflows/build.yml

Prepnuti na samostatnou CosmosDB

[ci] Use own CosmosDB instance

---

src/Sandbox.php

Same as https://github.com/keboola/sandboxes-api-php-client/pull/41

PS-3394 - feat: teradata type

---

src/Exception/InvalidArgumentException.php
src/MLDeployment.php
tests/ClientFunctionalTest.php
tests/MLDeploymentTest.php

https://keboola.atlassian.net/browse/PS-3258

PS-3258 add trackingTokenId field to deployments

---

src/ManageClient.php
tests/ManageClientUnitTest.php

Fix create project by sending PATCH empty project

Fix create project by sending PATCH empty project

---

src/Sandbox.php

https://keboola.atlassian.net/browse/PS-3810
Pridani Snowpark typu

PS-3810 Snowpark sandbox type

---

src/Sandbox.php

Fixes: https://keboola.atlassian.net/browse/BIG-66
Same as : https://github.com/keboola/sandboxes-api-php-client/pull/63

Sandbox type bigquery

---

.github/workflows/build.yml
composer.json
docker-compose.yml
src/Sandbox.php
src/SandboxCredentials.php
tests/ClientFunctionalAWSTest.php
tests/ClientFunctionalCredentialsTest.php
tests/ClientFunctionalTest.php
tests/DynamoTestCase.php
tests/SandboxCredentialsTest.php
tests/localstack/kms_seed.yaml

https://keboola.atlassian.net/browse/BIG-85
[BIG-85]: https://keboola.atlassian.net/browse/BIG-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BIG-85: sandbox credentials for BigQuery

---

src/Sandbox.php

Not to merge:). Miro I just put you as reviewer so you have an easy link to it

Add streamlit type to client

---

src/Sandbox.php

PST-867 make a new group for apps

---

.github/workflows/build.yml
README.md
composer.json
docker-compose.yml
src/Sandbox.php
tests/bootstrap.php

https://keboola.atlassian.net/browse/PST-938
For Data Apps we want to try two new Sizes (Micro and Tiny):
https://keboolaglobal.slack.com/archives/C04L6J6CWJJ/p1690795103309759
Product team will experiment with these two sizes to properly setup billing of Data Apps.

PST-938: TINY and MICRO size of container sandbox

---

src/Client.php
src/ManageClient.php
tests/ClientUnitTest.php
tests/ManageClientUnitTest.php

https://keboola.atlassian.net/browse/PST-1764
Pridani podpory pro `skipBillingReport` flag (https://github.com/keboola/sandboxes-api/blob/2e4bd235f3c31b638e9d4a4341b0a644f14a50c4/src/app.js#L31)

feat: Support for "skipBilling" flag
